import React from "react"

import "./book-content.style.css"
const BookContent = () => {
    let str = "Ahora hemos cubierto ampliamente cómo organizar sus tareas, proyectos, recordatorios e ideas, lo que significa que es hora de pasar al cuarto paso del proceso GTD: reflexionar.\nEl objetivo del método GTD es sentirse relajado y en control de todos sus proyectos actuales, realizar un seguimiento de ellos y asegurarse de que avanzan.\nPero para que esto suceda, es esencial que su sistema de productividad esté actualizado y completo en todo momento. Su mente solo estará tranquila y podrá concentrarse completamente en la tarea en cuestión si confía en su sistema. Y esto significa revisarlo de manera constante y frecuente.\nTodos los días, consulte su Calendario para conocer el terreno. Si está en reuniones todo el día, por ejemplo, tendrá un gran impacto en lo que puede hacer y debe saber esto antes de poder planificar su día.\nLuego, revise sus listas de Próximas Acciones para comprender qué tareas podría hacer en el contexto de ese día. Si pasa todo el día en la oficina, puede verificar qué tareas relacionadas con el teléfono o la computadora podría realizar.\nAdemás de esta revisión de inicio del día, probablemente se tomará unos segundos aquí y allá para revisar las listas cuando aparezca el contexto apropiado, por ejemplo, si se encuentra esperando en algún lugar inesperadamente.\nPero el verdadero pilar del sistema GTD es la revisión semanal completa.\nPara comenzar con esto, ate los cabos sueltos de la semana anterior, limpie sus herramientas de colección y capture cualquier pensamiento / idea que aún pueda estar dando vueltas en su cabeza. Además, revise su lista de Próximas Acciones, marcando los elementos completados.\nLuego pasa a revisar tu calendario. Es posible que se dé cuenta de que necesita preparar algo para las próximas citas, y las citas de la semana anterior pueden traer algunas ideas a su mente que desea capturar.\nAhora mire todas sus otras listas. ¿Hay algún elemento en la lista de espera que necesite seguimiento nuevamente?\n¿Y cómo se ve su lista de proyectos? Revise el estado, los planes y los materiales de cada proyecto y asegúrese de que todos tengan al menos una próxima acción en su sistema.\nFinalmente, mire su lista Algún día / Quizás. ¿Alguno de los elementos se ha vuelto tan interesante o relevante que desea seguir con ellos ahora? Si es así, conviértalos en proyectos. Pero también elimine elementos que ya no coincidan con sus intereses.\nDebe presupuestar algunas horas para la revisión semanal, pero la cantidad exacta de tiempo que necesita depende de cuánto necesite para sentirse seguro y confiar en su sistema. Dado que es fundamental para el éxito del sistema en su conjunto, debe desarrollar un hábito sólido de realizarlo cada semana. Podría planificar su revisión semanal, digamos, un viernes por la tarde, lo que le permitiría cerrar la tienda durante el fin de semana con la cabeza despejada y una sensación de control."

    return (
        <div className="book-content blur">
            <h2>Reflexione: Revisar constantemente su sistema es indispensable para trabajar de manera productiva.</h2>
            <p> {str} </p>
        </div>
    )
}

export default BookContent